import { ObjectType, LinkType, ActionType, DataFlow, BusinessRule, AIModel, AnalysisInsight } from './ontology';

// ----------------------------------------
// 语义层 (Semantic Layer)
// ----------------------------------------
export const ERP_OBJECT_TYPES: ObjectType[] = [
  {
    id: 'supplier-erp',
    apiName: 'Supplier',
    displayName: '供应商',
    description: '提供物料或服务的外部供应商',
    primaryKey: 'supplierId',
    titleKey: 'supplierName',
    visibility: 'GLOBAL',
    icon: 'Truck',
    layer: 'SEMANTIC',
    category: 'MASTER_DATA',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'supplierId', apiName: 'supplierId', displayName: '供应商编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'supplierName', apiName: 'supplierName', displayName: '供应商名称', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'creditRating', apiName: 'creditRating', displayName: '信用评级', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'paymentTerms', apiName: 'paymentTerms', displayName: '付款条件', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'status', apiName: 'status', displayName: '状态', baseType: 'STRING', visibility: 'NORMAL', required: true, description: 'ACTIVE/INACTIVE' },
    ],
  },
  {
    id: 'material-erp',
    apiName: 'Material',
    displayName: '物料',
    description: '采购的原材料、半成品或成品',
    primaryKey: 'materialCode',
    titleKey: 'materialName',
    visibility: 'GLOBAL',
    icon: 'Package',
    layer: 'SEMANTIC',
    category: 'MASTER_DATA',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'materialCode', apiName: 'materialCode', displayName: '物料编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'materialName', apiName: 'materialName', displayName: '物料名称', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'materialGroup', apiName: 'materialGroup', displayName: '物料组', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'baseUOM', apiName: 'baseUOM', displayName: '基本计量单位', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'standardPrice', apiName: 'standardPrice', displayName: '标准价格', baseType: 'DOUBLE', visibility: 'NORMAL', required: true },
    ],
  },
  {
    id: 'purchase-requisition',
    apiName: 'PurchaseRequisition',
    displayName: '采购申请 (PR)',
    description: '内部部门发起的采购需求凭证',
    primaryKey: 'prNumber',
    titleKey: 'prNumber',
    visibility: 'GLOBAL',
    icon: 'FileText',
    layer: 'SEMANTIC',
    category: 'TRANSACTION',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'prNumber', apiName: 'prNumber', displayName: 'PR编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'requestDate', apiName: 'requestDate', displayName: '申请日期', baseType: 'TIMESTAMP', visibility: 'PROMINENT', required: true },
      { id: 'requester', apiName: 'requester', displayName: '申请人', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'department', apiName: 'department', displayName: '需求部门', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'status', apiName: 'status', displayName: '审批状态', baseType: 'STRING', visibility: 'PROMINENT', required: true, description: 'DRAFT/PENDING/APPROVED/REJECTED' },
      { id: 'materialCode', apiName: 'materialCode', displayName: '物料编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'quantity', apiName: 'quantity', displayName: '需求数量', baseType: 'DOUBLE', visibility: 'PROMINENT', required: true },
      { id: 'requiredDate', apiName: 'requiredDate', displayName: '需求日期', baseType: 'TIMESTAMP', visibility: 'PROMINENT', required: true },
    ],
  },
  {
    id: 'purchase-order',
    apiName: 'PurchaseOrder',
    displayName: '采购订单 (PO)',
    description: '向供应商发出的正式采购合同',
    primaryKey: 'poNumber',
    titleKey: 'poNumber',
    visibility: 'GLOBAL',
    icon: 'ShoppingCart',
    layer: 'SEMANTIC',
    category: 'TRANSACTION',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'poNumber', apiName: 'poNumber', displayName: 'PO编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'orderDate', apiName: 'orderDate', displayName: '订单日期', baseType: 'TIMESTAMP', visibility: 'PROMINENT', required: true },
      { id: 'totalAmount', apiName: 'totalAmount', displayName: '总金额', baseType: 'DOUBLE', visibility: 'PROMINENT', required: true },
      { id: 'currency', apiName: 'currency', displayName: '币种', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'status', apiName: 'status', displayName: '订单状态', baseType: 'STRING', visibility: 'PROMINENT', required: true, description: 'CREATED/RELEASED/PARTIAL_RECEIPT/COMPLETED/CLOSED' },
      { id: 'supplierId', apiName: 'supplierId', displayName: '供应商编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'prNumber', apiName: 'prNumber', displayName: '来源PR编号', baseType: 'STRING', visibility: 'NORMAL', required: true },
    ],
  },
  {
    id: 'goods-receipt',
    apiName: 'GoodsReceipt',
    displayName: '收货单 (GR)',
    description: '仓库接收供应商货物的凭证',
    primaryKey: 'grNumber',
    titleKey: 'grNumber',
    visibility: 'GLOBAL',
    icon: 'Inbox',
    layer: 'SEMANTIC',
    category: 'TRANSACTION',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'grNumber', apiName: 'grNumber', displayName: 'GR编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'postingDate', apiName: 'postingDate', displayName: '过账日期', baseType: 'TIMESTAMP', visibility: 'PROMINENT', required: true },
      { id: 'receivedQuantity', apiName: 'receivedQuantity', displayName: '收货数量', baseType: 'DOUBLE', visibility: 'NORMAL', required: true },
      { id: 'qualityStatus', apiName: 'qualityStatus', displayName: '质检状态', baseType: 'STRING', visibility: 'NORMAL', required: true, description: 'UNRESTRICTED/IN_INSPECTION/BLOCKED' },
      { id: 'poNumber', apiName: 'poNumber', displayName: 'PO编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'deliveryNote', apiName: 'deliveryNote', displayName: '送货单号', baseType: 'STRING', visibility: 'NORMAL', required: true },
    ],
  },
  {
    id: 'invoice',
    apiName: 'Invoice',
    displayName: '发票 (INV)',
    description: '供应商提供的税务发票',
    primaryKey: 'invoiceNumber',
    titleKey: 'invoiceNumber',
    visibility: 'GLOBAL',
    icon: 'Receipt',
    layer: 'SEMANTIC',
    category: 'TRANSACTION',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
    properties: [
      { id: 'invoiceNumber', apiName: 'invoiceNumber', displayName: '发票号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'issueDate', apiName: 'issueDate', displayName: '开票日期', baseType: 'TIMESTAMP', visibility: 'NORMAL', required: true },
      { id: 'invoiceAmount', apiName: 'invoiceAmount', displayName: '发票金额', baseType: 'DOUBLE', visibility: 'PROMINENT', required: true },
      { id: 'taxAmount', apiName: 'taxAmount', displayName: '税额', baseType: 'DOUBLE', visibility: 'NORMAL', required: true },
      { id: 'status', apiName: 'status', displayName: '校验状态', baseType: 'STRING', visibility: 'PROMINENT', required: true, description: 'ENTERED/VERIFIED/BLOCKED/PAID' },
      { id: 'poNumber', apiName: 'poNumber', displayName: 'PO编号', baseType: 'STRING', visibility: 'NORMAL', required: true },
    ],
  },
];

export const ERP_LINK_TYPES: LinkType[] = [
  { id: 'link-pr-material', apiName: 'PRMaterial', displayName: '申请物料', description: '采购申请中包含的物料', sourceTypeId: 'purchase-requisition', targetTypeId: 'material-erp', cardinality: 'MANY_TO_ONE', foreignKeyPropertyId: 'materialCode', visibility: 'GLOBAL', layer: 'SEMANTIC', relationshipType: 'ASSOCIATION', createdAt: '2024-01-01T08:00:00Z', updatedAt: '2024-01-01T08:00:00Z', properties: [] },
  { id: 'link-po-supplier', apiName: 'POSupplier', displayName: '订单供应商', description: '采购订单关联的供应商', sourceTypeId: 'purchase-order', targetTypeId: 'supplier-erp', cardinality: 'MANY_TO_ONE', foreignKeyPropertyId: 'supplierId', visibility: 'GLOBAL', layer: 'SEMANTIC', relationshipType: 'ASSOCIATION', createdAt: '2024-01-01T08:00:00Z', updatedAt: '2024-01-01T08:00:00Z', properties: [] },
  { id: 'link-po-pr', apiName: 'POtoPR', displayName: '订单寻源', description: '采购订单来源的采购申请', sourceTypeId: 'purchase-order', targetTypeId: 'purchase-requisition', cardinality: 'MANY_TO_ONE', foreignKeyPropertyId: 'prNumber', visibility: 'GLOBAL', layer: 'SEMANTIC', relationshipType: 'ASSOCIATION', createdAt: '2024-01-01T08:00:00Z', updatedAt: '2024-01-01T08:00:00Z', properties: [] },
  { id: 'link-gr-po', apiName: 'GRtoPO', displayName: '收货关联订单', description: '收货单对应的采购订单', sourceTypeId: 'goods-receipt', targetTypeId: 'purchase-order', cardinality: 'MANY_TO_ONE', foreignKeyPropertyId: 'poNumber', visibility: 'GLOBAL', layer: 'SEMANTIC', relationshipType: 'ASSOCIATION', createdAt: '2024-01-01T08:00:00Z', updatedAt: '2024-01-01T08:00:00Z', properties: [] },
  { id: 'link-inv-po', apiName: 'InvoiceToPO', displayName: '发票关联订单', description: '发票对应的采购订单', sourceTypeId: 'invoice', targetTypeId: 'purchase-order', cardinality: 'MANY_TO_ONE', foreignKeyPropertyId: 'poNumber', visibility: 'GLOBAL', layer: 'SEMANTIC', relationshipType: 'ASSOCIATION', createdAt: '2024-01-01T08:00:00Z', updatedAt: '2024-01-01T08:00:00Z', properties: [] },
];

// ----------------------------------------
// 动势层 (Kinetic Layer)
// ----------------------------------------
export const ERP_ACTION_TYPES: ActionType[] = [
  {
    id: 'action-create-pr',
    apiName: 'CreatePR',
    displayName: '创建采购申请',
    description: '业务部门提报采购需求',
    affectedObjectTypeIds: ['purchase-requisition', 'material-erp'],
    affectedLinkTypeIds: ['link-pr-material'],
    inputParameters: [
      { id: 'materialCode', apiName: 'materialCode', displayName: '物料编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'quantity', apiName: 'quantity', displayName: '需求数量', baseType: 'DOUBLE', visibility: 'PROMINENT', required: true },
      { id: 'requiredDate', apiName: 'requiredDate', displayName: '需求日期', baseType: 'TIMESTAMP', visibility: 'PROMINENT', required: true },
    ],
    outputProperties: [
      { id: 'prNumber', apiName: 'prNumber', displayName: 'PR编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "CreatePurchaseRequisition",
      rootField: "createPurchaseRequisition",
      inputArgName: "input",
      inputFields: ["materialCode", "quantity", "requiredDate"],
      inputVarTypes: { materialCode: "String!", quantity: "Float!", requiredDate: "String!" },
      outputFields: ["prNumber"],
    },
    requiredRoles: ['REQUESTER', 'DEPARTMENT_MANAGER'],
    icon: 'FilePlus',
    color: '#3B82F6',
    visibility: 'GLOBAL',
    layer: 'KINETIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'action-create-po',
    apiName: 'CreatePO',
    displayName: '创建采购订单',
    description: '采购员将 PR 转换为正式 PO',
    affectedObjectTypeIds: ['purchase-order', 'purchase-requisition', 'supplier-erp'],
    affectedLinkTypeIds: ['link-po-pr', 'link-po-supplier'],
    inputParameters: [
      { id: 'prNumber', apiName: 'prNumber', displayName: 'PR编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'supplierId', apiName: 'supplierId', displayName: '供应商编码', baseType: 'STRING', visibility: 'PROMINENT', required: true },
    ],
    outputProperties: [
      { id: 'poNumber', apiName: 'poNumber', displayName: 'PO编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'status', apiName: 'status', displayName: '订单状态', baseType: 'STRING', visibility: 'PROMINENT', required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "CreatePurchaseOrder",
      rootField: "createPurchaseOrder",
      inputArgName: "input",
      inputFields: ["prNumber", "supplierId"],
      inputVarTypes: { prNumber: "String!", supplierId: "String!" },
      outputFields: ["poNumber", "status"],
    },
    triggerConditions: [
      { condition: 'pr.status == APPROVED', description: 'PR 必须已审批通过' },
    ],
    requiredRoles: ['BUYER'],
    icon: 'ShoppingCart',
    color: '#10B981',
    visibility: 'GLOBAL',
    layer: 'KINETIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'action-receive-goods',
    apiName: 'ReceiveGoods',
    displayName: '收货过账',
    description: '仓库接收供应商货物',
    affectedObjectTypeIds: ['goods-receipt', 'purchase-order'],
    affectedLinkTypeIds: ['link-gr-po'],
    inputParameters: [
      { id: 'poNumber', apiName: 'poNumber', displayName: 'PO编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
      { id: 'deliveryNote', apiName: 'deliveryNote', displayName: '送货单号', baseType: 'STRING', visibility: 'NORMAL', required: true },
      { id: 'receivedQuantity', apiName: 'receivedQuantity', displayName: '实收数量', baseType: 'DOUBLE', visibility: 'PROMINENT', required: true },
    ],
    outputProperties: [
      { id: 'grNumber', apiName: 'grNumber', displayName: 'GR编号', baseType: 'STRING', visibility: 'PROMINENT', required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "PostGoodsReceipt",
      rootField: "postGoodsReceipt",
      inputArgName: "input",
      inputFields: ["poNumber", "deliveryNote", "receivedQuantity"],
      inputVarTypes: { poNumber: "String!", deliveryNote: "String!", receivedQuantity: "Float!" },
      outputFields: ["grNumber"],
    },
    triggerConditions: [
      { condition: 'po.status == RELEASED || po.status == PARTIAL_RECEIPT', description: 'PO 必须是已下达且未完全收货状态' },
    ],
    requiredRoles: ['WAREHOUSE_CLERK'],
    icon: 'Inbox',
    color: '#F59E0B',
    visibility: 'GLOBAL',
    layer: 'KINETIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];

export const ERP_DATA_FLOWS: DataFlow[] = [
  {
    id: 'flow-p2p',
    apiName: 'ProcureToPay',
    displayName: '采购到付款 (P2P)',
    description: '端到端的企业采购流程',
    steps: [
      { stepOrder: 1, stepName: '需求提报', actionTypeId: 'action-create-pr', objectTypeId: 'purchase-requisition' },
      { stepOrder: 2, stepName: '寻源与订购', actionTypeId: 'action-create-po', objectTypeId: 'purchase-order', validation: 'pr.status == APPROVED' },
      { stepOrder: 3, stepName: '收货入库', actionTypeId: 'action-receive-goods', objectTypeId: 'goods-receipt' },
      { stepOrder: 4, stepName: '发票校验', objectTypeId: 'invoice', validation: 'three_way_match(po, gr, invoice) == TRUE' },
    ],
    flowDirection: 'FORWARD',
    visibility: 'GLOBAL',
    layer: 'KINETIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];

// ----------------------------------------
// 动态层 (Dynamic Layer)
// ----------------------------------------
export const ERP_BUSINESS_RULES: BusinessRule[] = [
  {
    id: 'rule-po-approval',
    apiName: 'POApprovalMatrix',
    displayName: '订单审批矩阵',
    description: '订单金额 > 100,000 需要采购总监审批',
    ruleType: 'VALIDATION',
    expression: 'IF po.totalAmount > 100000 THEN require_approval(DIRECTOR) ELSE require_approval(MANAGER)',
    appliesToObjectTypeIds: ['purchase-order'],
    priority: 90,
    enabled: true,
    visibility: 'GLOBAL',
    layer: 'DYNAMIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'rule-three-way-match',
    apiName: 'ThreeWayMatch',
    displayName: '三单匹配规则',
    description: '发票金额必须与收货数量和订单单价匹配 (允许5%容差)',
    ruleType: 'VALIDATION',
    expression: 'ABS(invoice.invoiceAmount - (gr.receivedQuantity * po.unitPrice)) <= (po.totalAmount * 0.05)',
    appliesToObjectTypeIds: ['invoice', 'goods-receipt', 'purchase-order'],
    onViolation: { action: 'BLOCK', message: '三单匹配失败，发票被冻结' },
    priority: 100,
    enabled: true,
    visibility: 'GLOBAL',
    layer: 'DYNAMIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];

export const ERP_AI_MODELS: AIModel[] = [
  {
    id: 'ai-supplier-eval',
    apiName: 'SupplierPerformanceEval',
    displayName: '供应商绩效评估',
    description: '综合评估供应商的交期准时率、质量合格率和价格优势',
    modelType: 'PREDICTION',
    inputFeatures: [
      { objectTypeId: 'supplier-erp', propertyIds: ['supplierId'] },
      { objectTypeId: 'goods-receipt', propertyIds: ['postingDate', 'qualityStatus'] },
      { objectTypeId: 'purchase-order', propertyIds: ['orderDate', 'totalAmount'] },
    ],
    outputType: 'SCORE',
    outputDescription: '百分制综合评分',
    modelSource: 'BUILT_IN',
    visibility: 'GLOBAL',
    layer: 'DYNAMIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];

export const ERP_ANALYSIS_INSIGHTS: AnalysisInsight[] = [
  {
    id: 'insight-spend',
    apiName: 'SpendAnalysis',
    displayName: '采购支出分析',
    description: '按物料组和供应商的支出汇总',
    insightType: 'DASHBOARD',
    dataSources: [
      { objectTypeId: 'purchase-order', propertyIds: ['totalAmount', 'currency'], aggregation: 'SUM' },
      { objectTypeId: 'supplier-erp', propertyIds: ['supplierName'] },
      { objectTypeId: 'material-erp', propertyIds: ['materialGroup'] },
    ],
    visualization: {
      chartType: 'PIE',
      dimensions: ['material.materialGroup'],
      measures: ['po.totalAmount_SUM'],
    },
    visibility: 'GLOBAL',
    layer: 'DYNAMIC',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];
