import { ObjectType, LinkType, ActionType, DataFlow, BusinessRule, AIModel, AnalysisInsight } from "./ontology";

export const SAP_HCM_OBJECT_TYPES: ObjectType[] = [
  {
    id: "employee-hcm",
    apiName: "Employee",
    displayName: "员工",
    description: "员工主数据（人员主数据）",
    primaryKey: "employeeId",
    titleKey: "fullName",
    visibility: "GLOBAL",
    icon: "User",
    layer: "SEMANTIC",
    category: "MASTER_DATA",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "fullName", apiName: "fullName", displayName: "姓名", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "firstName", apiName: "firstName", displayName: "名", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "lastName", apiName: "lastName", displayName: "姓", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "email", apiName: "email", displayName: "邮箱", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "phone", apiName: "phone", displayName: "电话", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "status", apiName: "status", displayName: "人员状态", baseType: "STRING", visibility: "PROMINENT", required: true, description: "ACTIVE/INACTIVE/TERMINATED" },
      { id: "hireDate", apiName: "hireDate", displayName: "入职日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "terminationDate", apiName: "terminationDate", displayName: "离职日期", baseType: "TIMESTAMP", visibility: "NORMAL", required: false },
      { id: "orgUnitId", apiName: "orgUnitId", displayName: "组织单元ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "positionId", apiName: "positionId", displayName: "岗位ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "costCenterId", apiName: "costCenterId", displayName: "成本中心ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "managerEmployeeId", apiName: "managerEmployeeId", displayName: "直属上级员工编号", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "payrollAreaId", apiName: "payrollAreaId", displayName: "薪资范围ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "personnelAreaId", apiName: "personnelAreaId", displayName: "人事范围ID", baseType: "STRING", visibility: "NORMAL", required: true },
    ],
  },
  {
    id: "org-unit-hcm",
    apiName: "OrgUnit",
    displayName: "组织单元",
    description: "组织结构中的部门/组织单元",
    primaryKey: "orgUnitId",
    titleKey: "orgUnitName",
    visibility: "GLOBAL",
    icon: "Building2",
    layer: "SEMANTIC",
    category: "MASTER_DATA",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "orgUnitId", apiName: "orgUnitId", displayName: "组织单元ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "orgUnitName", apiName: "orgUnitName", displayName: "组织单元名称", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "orgUnitType", apiName: "orgUnitType", displayName: "类型", baseType: "STRING", visibility: "NORMAL", required: true, description: "COMPANY/DIVISION/DEPARTMENT/TEAM" },
      { id: "parentOrgUnitId", apiName: "parentOrgUnitId", displayName: "上级组织单元ID", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "costCenterId", apiName: "costCenterId", displayName: "成本中心ID", baseType: "STRING", visibility: "NORMAL", required: true },
    ],
  },
  {
    id: "position-hcm",
    apiName: "Position",
    displayName: "岗位",
    description: "组织中的岗位（Position）",
    primaryKey: "positionId",
    titleKey: "positionTitle",
    visibility: "GLOBAL",
    icon: "Briefcase",
    layer: "SEMANTIC",
    category: "MASTER_DATA",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "positionId", apiName: "positionId", displayName: "岗位ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "positionTitle", apiName: "positionTitle", displayName: "岗位名称", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "orgUnitId", apiName: "orgUnitId", displayName: "所属组织单元ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "jobId", apiName: "jobId", displayName: "职位族ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "costCenterId", apiName: "costCenterId", displayName: "成本中心ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "status", apiName: "status", displayName: "岗位状态", baseType: "STRING", visibility: "NORMAL", required: true, description: "OPEN/FILLED/CLOSED" },
    ],
  },
  {
    id: "job-hcm",
    apiName: "Job",
    displayName: "职位族",
    description: "岗位的岗位族/序列（Job）",
    primaryKey: "jobId",
    titleKey: "jobName",
    visibility: "GLOBAL",
    icon: "Layers",
    layer: "SEMANTIC",
    category: "REFERENCE",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "jobId", apiName: "jobId", displayName: "职位族ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "jobName", apiName: "jobName", displayName: "职位族名称", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "jobFamily", apiName: "jobFamily", displayName: "岗位族", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "gradeLevel", apiName: "gradeLevel", displayName: "职级", baseType: "STRING", visibility: "NORMAL", required: true },
    ],
  },
  {
    id: "cost-center-hcm",
    apiName: "CostCenter",
    displayName: "成本中心",
    description: "财务维度的成本中心，用于成本归集与核算",
    primaryKey: "costCenterId",
    titleKey: "costCenterName",
    visibility: "GLOBAL",
    icon: "Landmark",
    layer: "SEMANTIC",
    category: "REFERENCE",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "costCenterId", apiName: "costCenterId", displayName: "成本中心ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "costCenterName", apiName: "costCenterName", displayName: "成本中心名称", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "companyCode", apiName: "companyCode", displayName: "公司代码", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "currency", apiName: "currency", displayName: "币种", baseType: "STRING", visibility: "NORMAL", required: true, defaultValue: "CNY" },
    ],
  },
  {
    id: "employment-hcm",
    apiName: "Employment",
    displayName: "雇佣关系",
    description: "员工与雇佣的有效期与用工类型信息",
    primaryKey: "employmentId",
    titleKey: "employmentId",
    visibility: "GLOBAL",
    icon: "FileBadge",
    layer: "SEMANTIC",
    category: "TRANSACTION",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "employmentId", apiName: "employmentId", displayName: "雇佣ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "employmentType", apiName: "employmentType", displayName: "用工类型", baseType: "STRING", visibility: "PROMINENT", required: true, description: "FULL_TIME/PART_TIME/INTERN/CONTRACTOR" },
      { id: "startDate", apiName: "startDate", displayName: "生效日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "endDate", apiName: "endDate", displayName: "失效日期", baseType: "TIMESTAMP", visibility: "NORMAL", required: false },
      { id: "status", apiName: "status", displayName: "雇佣状态", baseType: "STRING", visibility: "NORMAL", required: true, description: "ACTIVE/SUSPENDED/ENDED" },
    ],
  },
  {
    id: "time-entry-hcm",
    apiName: "TimeEntry",
    displayName: "工时记录",
    description: "工时与考勤的明细记录",
    primaryKey: "timeEntryId",
    titleKey: "timeEntryId",
    visibility: "GLOBAL",
    icon: "Clock",
    layer: "SEMANTIC",
    category: "TRANSACTION",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "timeEntryId", apiName: "timeEntryId", displayName: "工时记录ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "workDate", apiName: "workDate", displayName: "日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "hours", apiName: "hours", displayName: "工时", baseType: "DOUBLE", visibility: "PROMINENT", required: true },
      { id: "timeType", apiName: "timeType", displayName: "工时类型", baseType: "STRING", visibility: "NORMAL", required: true, description: "WORK/OVERTIME/LEAVE" },
      { id: "status", apiName: "status", displayName: "状态", baseType: "STRING", visibility: "NORMAL", required: true, description: "DRAFT/SUBMITTED/APPROVED/REJECTED" },
    ],
  },
  {
    id: "absence-request-hcm",
    apiName: "AbsenceRequest",
    displayName: "请假申请",
    description: "员工请假/休假申请单",
    primaryKey: "requestId",
    titleKey: "requestId",
    visibility: "GLOBAL",
    icon: "CalendarMinus",
    layer: "SEMANTIC",
    category: "TRANSACTION",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "requestId", apiName: "requestId", displayName: "申请单ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "absenceType", apiName: "absenceType", displayName: "请假类型", baseType: "STRING", visibility: "PROMINENT", required: true, description: "ANNUAL/SICK/PERSONAL/MATERNITY/OTHER" },
      { id: "startDate", apiName: "startDate", displayName: "开始日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "endDate", apiName: "endDate", displayName: "结束日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "status", apiName: "status", displayName: "审批状态", baseType: "STRING", visibility: "PROMINENT", required: true, description: "DRAFT/PENDING/APPROVED/REJECTED/CANCELLED" },
      { id: "approverEmployeeId", apiName: "approverEmployeeId", displayName: "审批人员工编号", baseType: "STRING", visibility: "NORMAL", required: false },
      { id: "approvedAt", apiName: "approvedAt", displayName: "审批时间", baseType: "TIMESTAMP", visibility: "NORMAL", required: false },
    ],
  },
  {
    id: "payroll-run-hcm",
    apiName: "PayrollRun",
    displayName: "跑薪批次",
    description: "按薪资范围与期间执行一次跑薪计算的批次",
    primaryKey: "payrollRunId",
    titleKey: "payrollRunId",
    visibility: "GLOBAL",
    icon: "Calculator",
    layer: "SEMANTIC",
    category: "TRANSACTION",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "payrollRunId", apiName: "payrollRunId", displayName: "跑薪批次ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "payrollAreaId", apiName: "payrollAreaId", displayName: "薪资范围ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "periodStart", apiName: "periodStart", displayName: "期间开始", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "periodEnd", apiName: "periodEnd", displayName: "期间结束", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "runDate", apiName: "runDate", displayName: "运行时间", baseType: "TIMESTAMP", visibility: "NORMAL", required: true },
      { id: "status", apiName: "status", displayName: "状态", baseType: "STRING", visibility: "PROMINENT", required: true, description: "CREATED/RUNNING/COMPLETED/FAILED" },
    ],
  },
  {
    id: "payroll-result-hcm",
    apiName: "PayrollResult",
    displayName: "薪资结果",
    description: "跑薪批次输出的员工级薪资结果",
    primaryKey: "payrollResultId",
    titleKey: "payrollResultId",
    visibility: "GLOBAL",
    icon: "Receipt",
    layer: "SEMANTIC",
    category: "TRANSACTION",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    properties: [
      { id: "payrollResultId", apiName: "payrollResultId", displayName: "薪资结果ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "payrollRunId", apiName: "payrollRunId", displayName: "跑薪批次ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "grossPay", apiName: "grossPay", displayName: "税前薪资", baseType: "DOUBLE", visibility: "PROMINENT", required: true },
      { id: "netPay", apiName: "netPay", displayName: "税后薪资", baseType: "DOUBLE", visibility: "PROMINENT", required: true },
      { id: "currency", apiName: "currency", displayName: "币种", baseType: "STRING", visibility: "NORMAL", required: true, defaultValue: "CNY" },
      { id: "paymentDate", apiName: "paymentDate", displayName: "发薪日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
    ],
  },
];

export const SAP_HCM_LINK_TYPES: LinkType[] = [
  { id: "link-employee-orgunit", apiName: "EmployeeOrgUnit", displayName: "所属组织", description: "员工所属组织单元", sourceTypeId: "employee-hcm", targetTypeId: "org-unit-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "orgUnitId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-employee-position", apiName: "EmployeePosition", displayName: "任职岗位", description: "员工当前任职的岗位", sourceTypeId: "employee-hcm", targetTypeId: "position-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "positionId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-employee-costcenter", apiName: "EmployeeCostCenter", displayName: "成本归属", description: "员工成本归属到成本中心", sourceTypeId: "employee-hcm", targetTypeId: "cost-center-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "costCenterId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-orgunit-parent", apiName: "OrgUnitParent", displayName: "上级组织", description: "组织单元的上级组织单元", sourceTypeId: "org-unit-hcm", targetTypeId: "org-unit-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "parentOrgUnitId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-orgunit-costcenter", apiName: "OrgUnitCostCenter", displayName: "组织成本中心", description: "组织单元绑定成本中心", sourceTypeId: "org-unit-hcm", targetTypeId: "cost-center-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "costCenterId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-position-orgunit", apiName: "PositionOrgUnit", displayName: "岗位所属组织", description: "岗位所属的组织单元", sourceTypeId: "position-hcm", targetTypeId: "org-unit-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "orgUnitId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-position-job", apiName: "PositionJob", displayName: "岗位职位族", description: "岗位对应职位族", sourceTypeId: "position-hcm", targetTypeId: "job-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "jobId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-employment-employee", apiName: "EmploymentEmployee", displayName: "雇佣关联员工", description: "雇佣关系绑定员工", sourceTypeId: "employment-hcm", targetTypeId: "employee-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "employeeId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-timeentry-employee", apiName: "TimeEntryEmployee", displayName: "工时关联员工", description: "工时记录关联员工", sourceTypeId: "time-entry-hcm", targetTypeId: "employee-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "employeeId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-absence-employee", apiName: "AbsenceEmployee", displayName: "请假人", description: "请假申请关联员工", sourceTypeId: "absence-request-hcm", targetTypeId: "employee-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "employeeId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-absence-approver", apiName: "AbsenceApprover", displayName: "审批人", description: "请假审批人（员工）", sourceTypeId: "absence-request-hcm", targetTypeId: "employee-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "approverEmployeeId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-payrollresult-run", apiName: "PayrollResultRun", displayName: "结果所属跑薪批次", description: "薪资结果属于某次跑薪批次", sourceTypeId: "payroll-result-hcm", targetTypeId: "payroll-run-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "payrollRunId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
  { id: "link-payrollresult-employee", apiName: "PayrollResultEmployee", displayName: "结果对应员工", description: "薪资结果对应员工", sourceTypeId: "payroll-result-hcm", targetTypeId: "employee-hcm", cardinality: "MANY_TO_ONE", foreignKeyPropertyId: "employeeId", visibility: "GLOBAL", layer: "SEMANTIC", relationshipType: "ASSOCIATION", createdAt: "2024-01-01T08:00:00Z", updatedAt: "2024-01-01T08:00:00Z", properties: [] },
];

export const SAP_HCM_ACTION_TYPES: ActionType[] = [
  {
    id: "action-hire-employee",
    apiName: "HireEmployee",
    displayName: "员工入职",
    description: "创建员工主数据并生成雇佣关系",
    affectedObjectTypeIds: ["employee-hcm", "employment-hcm"],
    affectedLinkTypeIds: ["link-employment-employee", "link-employee-orgunit", "link-employee-position", "link-employee-costcenter"],
    inputParameters: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "fullName", apiName: "fullName", displayName: "姓名", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "orgUnitId", apiName: "orgUnitId", displayName: "组织单元ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "positionId", apiName: "positionId", displayName: "岗位ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "costCenterId", apiName: "costCenterId", displayName: "成本中心ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "payrollAreaId", apiName: "payrollAreaId", displayName: "薪资范围ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "personnelAreaId", apiName: "personnelAreaId", displayName: "人事范围ID", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "employmentType", apiName: "employmentType", displayName: "用工类型", baseType: "STRING", visibility: "NORMAL", required: true },
      { id: "hireDate", apiName: "hireDate", displayName: "入职日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
    ],
    outputProperties: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "status", apiName: "status", displayName: "人员状态", baseType: "STRING", visibility: "PROMINENT", required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "HireEmployee",
      rootField: "hireEmployee",
      inputArgName: "input",
      inputFields: ["employeeId", "fullName", "orgUnitId", "positionId", "costCenterId", "payrollAreaId", "personnelAreaId", "employmentType", "hireDate"],
      inputVarTypes: {
        employeeId: "String!",
        fullName: "String!",
        orgUnitId: "String!",
        positionId: "String!",
        costCenterId: "String!",
        payrollAreaId: "String!",
        personnelAreaId: "String!",
        employmentType: "String!",
        hireDate: "String!",
      },
      outputFields: ["employeeId", "status"],
    },
    requiredRoles: ["HR_ADMIN"],
    icon: "UserPlus",
    color: "#3B82F6",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "action-transfer-employee",
    apiName: "TransferEmployee",
    displayName: "员工调岗",
    description: "调整员工的组织单元与岗位",
    affectedObjectTypeIds: ["employee-hcm"],
    affectedLinkTypeIds: ["link-employee-orgunit", "link-employee-position"],
    inputParameters: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "orgUnitId", apiName: "orgUnitId", displayName: "新组织单元ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "positionId", apiName: "positionId", displayName: "新岗位ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "effectiveDate", apiName: "effectiveDate", displayName: "生效日期", baseType: "TIMESTAMP", visibility: "NORMAL", required: true },
    ],
    outputProperties: [{ id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true }],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "TransferEmployee",
      rootField: "transferEmployee",
      inputArgName: "input",
      inputFields: ["employeeId", "orgUnitId", "positionId", "effectiveDate"],
      inputVarTypes: { employeeId: "String!", orgUnitId: "String!", positionId: "String!", effectiveDate: "String!" },
      outputFields: ["employeeId"],
    },
    requiredRoles: ["HR_ADMIN", "HR_SPECIALIST"],
    icon: "ArrowLeftRight",
    color: "#10B981",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "action-record-time-entry",
    apiName: "RecordTimeEntry",
    displayName: "记录工时",
    description: "新增工时记录用于考勤与薪资计算",
    affectedObjectTypeIds: ["time-entry-hcm"],
    affectedLinkTypeIds: ["link-timeentry-employee"],
    inputParameters: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "workDate", apiName: "workDate", displayName: "日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "hours", apiName: "hours", displayName: "工时", baseType: "DOUBLE", visibility: "PROMINENT", required: true },
      { id: "timeType", apiName: "timeType", displayName: "工时类型", baseType: "STRING", visibility: "NORMAL", required: true },
    ],
    outputProperties: [{ id: "timeEntryId", apiName: "timeEntryId", displayName: "工时记录ID", baseType: "STRING", visibility: "PROMINENT", required: true }],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "RecordTimeEntry",
      rootField: "recordTimeEntry",
      inputArgName: "input",
      inputFields: ["employeeId", "workDate", "hours", "timeType"],
      inputVarTypes: { employeeId: "String!", workDate: "String!", hours: "Float!", timeType: "String!" },
      outputFields: ["timeEntryId"],
    },
    requiredRoles: ["EMPLOYEE", "MANAGER"],
    icon: "Clock",
    color: "#F59E0B",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "action-request-absence",
    apiName: "RequestAbsence",
    displayName: "发起请假",
    description: "提交请假申请并进入审批流程",
    affectedObjectTypeIds: ["absence-request-hcm"],
    affectedLinkTypeIds: ["link-absence-employee"],
    inputParameters: [
      { id: "employeeId", apiName: "employeeId", displayName: "员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "absenceType", apiName: "absenceType", displayName: "请假类型", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "startDate", apiName: "startDate", displayName: "开始日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "endDate", apiName: "endDate", displayName: "结束日期", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
    ],
    outputProperties: [
      { id: "requestId", apiName: "requestId", displayName: "申请单ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "status", apiName: "status", displayName: "审批状态", baseType: "STRING", visibility: "PROMINENT", required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "RequestAbsence",
      rootField: "requestAbsence",
      inputArgName: "input",
      inputFields: ["employeeId", "absenceType", "startDate", "endDate"],
      inputVarTypes: { employeeId: "String!", absenceType: "String!", startDate: "String!", endDate: "String!" },
      outputFields: ["requestId", "status"],
    },
    requiredRoles: ["EMPLOYEE"],
    icon: "CalendarMinus",
    color: "#8B5CF6",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "action-approve-absence",
    apiName: "ApproveAbsence",
    displayName: "审批请假",
    description: "经理审批请假申请并更新状态",
    affectedObjectTypeIds: ["absence-request-hcm"],
    affectedLinkTypeIds: ["link-absence-approver"],
    inputParameters: [
      { id: "requestId", apiName: "requestId", displayName: "申请单ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "approverEmployeeId", apiName: "approverEmployeeId", displayName: "审批人员工编号", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "decision", apiName: "decision", displayName: "决策", baseType: "STRING", visibility: "PROMINENT", required: true, description: "APPROVE/REJECT" },
    ],
    outputProperties: [
      { id: "requestId", apiName: "requestId", displayName: "申请单ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "status", apiName: "status", displayName: "审批状态", baseType: "STRING", visibility: "PROMINENT", required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "ApproveAbsence",
      rootField: "approveAbsence",
      inputArgName: "input",
      inputFields: ["requestId", "approverEmployeeId", "decision"],
      inputVarTypes: { requestId: "String!", approverEmployeeId: "String!", decision: "String!" },
      outputFields: ["requestId", "status"],
    },
    requiredRoles: ["MANAGER"],
    icon: "CheckCircle2",
    color: "#22C55E",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "action-run-payroll",
    apiName: "RunPayroll",
    displayName: "运行薪资计算",
    description: "对指定薪资范围与期间执行跑薪并生成结果",
    affectedObjectTypeIds: ["payroll-run-hcm", "payroll-result-hcm"],
    affectedLinkTypeIds: ["link-payrollresult-run", "link-payrollresult-employee"],
    inputParameters: [
      { id: "payrollAreaId", apiName: "payrollAreaId", displayName: "薪资范围ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "periodStart", apiName: "periodStart", displayName: "期间开始", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
      { id: "periodEnd", apiName: "periodEnd", displayName: "期间结束", baseType: "TIMESTAMP", visibility: "PROMINENT", required: true },
    ],
    outputProperties: [
      { id: "payrollRunId", apiName: "payrollRunId", displayName: "跑薪批次ID", baseType: "STRING", visibility: "PROMINENT", required: true },
      { id: "status", apiName: "status", displayName: "状态", baseType: "STRING", visibility: "PROMINENT", required: true },
    ],
    interfaceMapping: {
      kind: "GRAPHQL",
      operationType: "mutation",
      operationName: "RunPayroll",
      rootField: "runPayroll",
      inputArgName: "input",
      inputFields: ["payrollAreaId", "periodStart", "periodEnd"],
      inputVarTypes: { payrollAreaId: "String!", periodStart: "String!", periodEnd: "String!" },
      outputFields: ["payrollRunId", "status"],
    },
    requiredRoles: ["PAYROLL_ADMIN"],
    icon: "Calculator",
    color: "#0EA5E9",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export const SAP_HCM_DATA_FLOWS: DataFlow[] = [
  {
    id: "df-hire-onboarding",
    apiName: "HireOnboardingFlow",
    displayName: "入职与主数据建立",
    description: "从入职动作建立员工主数据与雇佣关系，并同步到后续模块",
    steps: [
      { stepOrder: 1, stepName: "创建员工主数据", actionTypeId: "action-hire-employee", objectTypeId: "employee-hcm", validation: "员工编号唯一；组织/岗位存在" },
      { stepOrder: 2, stepName: "创建雇佣关系", actionTypeId: "action-hire-employee", objectTypeId: "employment-hcm", validation: "同一员工仅允许一个 ACTIVE 雇佣" },
    ],
    flowDirection: "FORWARD",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "df-time-to-payroll",
    apiName: "TimeToPayrollFlow",
    displayName: "工时到薪资计算",
    description: "工时/请假数据进入跑薪批次并产出薪资结果",
    steps: [
      { stepOrder: 1, stepName: "记录工时", actionTypeId: "action-record-time-entry", objectTypeId: "time-entry-hcm", validation: "工时>=0 且日期在期间内" },
      { stepOrder: 2, stepName: "审批请假", actionTypeId: "action-approve-absence", objectTypeId: "absence-request-hcm", validation: "仅 PENDING 可审批" },
      { stepOrder: 3, stepName: "运行跑薪", actionTypeId: "action-run-payroll", objectTypeId: "payroll-run-hcm", transformation: "汇总期间内工时/请假，计算薪资结果" },
    ],
    flowDirection: "FORWARD",
    visibility: "GLOBAL",
    layer: "KINETIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export const SAP_HCM_BUSINESS_RULES: BusinessRule[] = [
  {
    id: "rule-employee-required-assignments",
    apiName: "EmployeeMustHaveOrgAndPosition",
    displayName: "员工必须具备组织与岗位",
    description: "员工主数据必须绑定组织单元与岗位，且二者必须存在",
    ruleType: "CONSTRAINT",
    expression: "Employee.orgUnitId != null AND Employee.positionId != null",
    appliesToObjectTypeIds: ["employee-hcm"],
    appliesToActionTypeIds: ["action-hire-employee", "action-transfer-employee"],
    onViolation: { action: "BLOCK", message: "员工必须分配组织单元与岗位" },
    priority: 90,
    enabled: true,
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "rule-one-active-employment",
    apiName: "OneActiveEmploymentPerEmployee",
    displayName: "同一员工仅允许一个有效雇佣",
    description: "员工在任何时刻仅允许一个 ACTIVE 雇佣关系",
    ruleType: "VALIDATION",
    expression: "count(Employment where employeeId = :employeeId and status='ACTIVE') <= 1",
    appliesToObjectTypeIds: ["employment-hcm"],
    appliesToActionTypeIds: ["action-hire-employee"],
    onViolation: { action: "BLOCK", message: "同一员工存在多个有效雇佣，请先结束旧雇佣" },
    priority: 80,
    enabled: true,
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "rule-absence-date-range",
    apiName: "AbsenceDateRangeValid",
    displayName: "请假日期范围校验",
    description: "请假开始日期必须小于等于结束日期",
    ruleType: "VALIDATION",
    expression: "AbsenceRequest.startDate <= AbsenceRequest.endDate",
    appliesToObjectTypeIds: ["absence-request-hcm"],
    appliesToActionTypeIds: ["action-request-absence"],
    onViolation: { action: "BLOCK", message: "请假日期范围不合法" },
    priority: 70,
    enabled: true,
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
  {
    id: "rule-absence-approval-transition",
    apiName: "AbsenceApprovalTransition",
    displayName: "请假审批状态流转",
    description: "仅 PENDING 状态允许审批，审批后状态变为 APPROVED/REJECTED",
    ruleType: "CONSTRAINT",
    expression: "AbsenceRequest.status in ['PENDING'] before ApproveAbsence",
    appliesToObjectTypeIds: ["absence-request-hcm"],
    appliesToActionTypeIds: ["action-approve-absence"],
    onViolation: { action: "BLOCK", message: "仅待审批状态允许审批" },
    priority: 75,
    enabled: true,
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export const SAP_HCM_AI_MODELS: AIModel[] = [
  {
    id: "model-absence-risk",
    apiName: "AbsenceRiskPrediction",
    displayName: "缺勤风险预测",
    description: "基于历史请假与工时行为预测短期缺勤风险",
    modelType: "PREDICTION",
    inputFeatures: [
      { objectTypeId: "absence-request-hcm", propertyIds: ["absenceType", "startDate", "endDate"], featureDescription: "请假类型与时长" },
      { objectTypeId: "time-entry-hcm", propertyIds: ["hours", "workDate", "timeType"], featureDescription: "工时变化与加班" },
    ],
    outputType: "SCORE",
    outputDescription: "0-1 风险分",
    modelConfig: { algorithm: "xgboost", threshold: 0.7 },
    modelSource: "BUILT_IN",
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];

export const SAP_HCM_ANALYSIS_INSIGHTS: AnalysisInsight[] = [
  {
    id: "insight-headcount-by-org",
    apiName: "HeadcountByOrgUnit",
    displayName: "组织人头数",
    description: "按组织单元统计在岗员工数量",
    insightType: "METRIC",
    dataSources: [{ objectTypeId: "employee-hcm", propertyIds: ["employeeId", "orgUnitId", "status"], aggregation: "COUNT_DISTINCT" }],
    visualization: { chartType: "BAR", dimensions: ["orgUnitId"], measures: ["count(employeeId)"] },
    refreshFrequency: "DAILY",
    visibility: "GLOBAL",
    layer: "DYNAMIC",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
  },
];
