import { MetaCore } from "@/lib/meta/meta-core";
import { Property } from "@/lib/types/ontology";
import { toSnakeCase } from "@/lib/utils";
import { OrmLinkMapping, OrmMapping, OrmTableMapping, PrimaryKeyStrategy } from "@/lib/orm/orm-mapping";

function quoteIdent(name: string) {
  return `"${name.replace(/"/g, '""')}"`;
}

function pgTypeForBaseType(baseType: string | undefined) {
  switch (baseType) {
    case "STRING":
      return "text";
    case "INTEGER":
      return "integer";
    case "DOUBLE":
      return "double precision";
    case "BOOLEAN":
      return "boolean";
    case "TIMESTAMP":
      return "timestamptz";
    case "STRUCT":
      return "jsonb";
    default:
      return "text";
  }
}

function guessPrimaryKeyPropertyId(objectTypeId: string, meta: MetaCore) {
  const ot = meta.objectTypes.find((o) => o.id === objectTypeId);
  if (!ot) return undefined;
  if (ot.primaryKey && ot.properties.some((p) => p.id === ot.primaryKey)) return ot.primaryKey;
  const idProp = ot.properties.find((p) => p.apiName === "id");
  return idProp?.id;
}

function defaultTableName(otApiName: string) {
  return toSnakeCase(otApiName);
}

function defaultColumnName(propertyApiName: string) {
  return toSnakeCase(propertyApiName);
}

export function buildDefaultOrmMapping(meta: MetaCore): OrmMapping {
  const tables: Record<string, OrmTableMapping> = {};
  const links: Record<string, OrmLinkMapping> = {};

  for (const ot of meta.objectTypes || []) {
    const pkPropertyId = guessPrimaryKeyPropertyId(ot.id, meta);
    const primaryKeyStrategy: PrimaryKeyStrategy = pkPropertyId ? "PROPERTY" : "UUID";
    const columns: Record<string, any> = {};
    for (const p of ot.properties || []) {
      columns[p.id] = {
        propertyId: p.id,
        columnName: defaultColumnName(p.apiName || p.id),
      };
    }
    tables[ot.id] = {
      objectTypeId: ot.id,
      tableName: defaultTableName(ot.apiName || ot.id),
      primaryKeyStrategy,
      primaryKeyPropertyId: pkPropertyId,
      primaryKeyColumnName: primaryKeyStrategy === "UUID" ? "id" : undefined,
      columns,
    };
  }

  for (const lt of meta.linkTypes || []) {
    links[lt.id] = {
      linkTypeId: lt.id,
      cardinality: lt.cardinality,
      foreignKeyPlacement: "SOURCE",
      foreignKeyColumnName: undefined,
      joinTableName: undefined,
      joinSourceColumnName: undefined,
      joinTargetColumnName: undefined,
    };
  }

  return { dialect: "postgres", tables, links };
}

function resolveTable(meta: MetaCore, mapping: OrmMapping, objectTypeId: string) {
  const ot = meta.objectTypes.find((o) => o.id === objectTypeId);
  const table = mapping.tables[objectTypeId];
  if (!ot || !table) return null;
  return { ot, table };
}

function resolveProperty(otId: string, propertyId: string, meta: MetaCore) {
  const ot = meta.objectTypes.find((o) => o.id === otId);
  if (!ot) return null;
  const p = (ot.properties || []).find((x) => x.id === propertyId);
  if (!p) return null;
  return { ot, p };
}

function sqlTypeForProperty(p: Property, override?: string) {
  if (override?.trim()) return override.trim();
  return pgTypeForBaseType(String((p as any)?.baseType));
}

function computePkColumn(meta: MetaCore, mapping: OrmMapping, objectTypeId: string) {
  const resolved = resolveTable(meta, mapping, objectTypeId);
  if (!resolved) return { columnName: "id", sqlType: "uuid" };
  const { table, ot } = resolved;

  if (table.primaryKeyStrategy === "UUID") {
    return { columnName: table.primaryKeyColumnName || "id", sqlType: "uuid" };
  }

  const pkPropId = table.primaryKeyPropertyId || ot.primaryKey || guessPrimaryKeyPropertyId(objectTypeId, meta);
  if (!pkPropId) return { columnName: table.primaryKeyColumnName || "id", sqlType: "uuid" };
  const propResolved = resolveProperty(objectTypeId, pkPropId, meta);
  if (!propResolved) return { columnName: table.primaryKeyColumnName || "id", sqlType: "uuid" };
  const col = table.columns[pkPropId];
  const colName = table.primaryKeyColumnName || col?.columnName || defaultColumnName(propResolved.p.apiName || pkPropId);
  const colType = sqlTypeForProperty(propResolved.p, col?.sqlType);
  return { columnName: colName, sqlType: colType };
}

export function generatePostgresDDL(meta: MetaCore, mapping?: OrmMapping) {
  const effectiveMapping = mapping || buildDefaultOrmMapping(meta);
  const lines: string[] = [];
  const warnings: string[] = [];

  lines.push(`-- Generated by Ontology Simulator (Meta → Postgres DDL)`);
  lines.push(``);

  for (const ot of meta.objectTypes || []) {
    const table = effectiveMapping.tables[ot.id];
    if (!table) continue;

    const tableName = table.tableName || defaultTableName(ot.apiName || ot.id);
    const pk = computePkColumn(meta, effectiveMapping, ot.id);

    lines.push(`create table if not exists ${quoteIdent(tableName)} (`);
    const colLines: string[] = [];
    const usedColumns = new Set<string>();

    const addColumn = (name: string, sqlType: string, nullable: boolean) => {
      const key = name.toLowerCase();
      if (usedColumns.has(key)) return;
      usedColumns.add(key);
      colLines.push(`  ${quoteIdent(name)} ${sqlType}${nullable ? "" : " not null"}`);
    };

    if (table.primaryKeyStrategy === "UUID") {
      addColumn(pk.columnName, pk.sqlType, false);
    }

    for (const p of ot.properties || []) {
      const col = table.columns[p.id];
      if (!col) continue;
      const isPk =
        table.primaryKeyStrategy === "PROPERTY" &&
        (table.primaryKeyPropertyId || ot.primaryKey) &&
        p.id === (table.primaryKeyPropertyId || ot.primaryKey);

      const colName = isPk ? pk.columnName : col.columnName || defaultColumnName(p.apiName || p.id);
      const sqlType = sqlTypeForProperty(p, col.sqlType);

      addColumn(colName, sqlType, isPk ? false : !(p as any)?.required);
    }

    colLines.push(`  primary key (${quoteIdent(pk.columnName)})`);

    lines.push(colLines.join(",\n"));
    lines.push(`);`);
    lines.push(``);
  }

  for (const lt of meta.linkTypes || []) {
    const linkMap = effectiveMapping.links[lt.id];
    if (!linkMap) continue;

    const sourceResolved = resolveTable(meta, effectiveMapping, lt.sourceTypeId);
    const targetResolved = resolveTable(meta, effectiveMapping, lt.targetTypeId);
    if (!sourceResolved || !targetResolved) continue;

    const sourceTable = sourceResolved.table.tableName;
    const targetTable = targetResolved.table.tableName;
    const sourcePk = computePkColumn(meta, effectiveMapping, lt.sourceTypeId);
    const targetPk = computePkColumn(meta, effectiveMapping, lt.targetTypeId);

    if (lt.cardinality === "MANY_TO_MANY") {
      const joinTableName =
        linkMap.joinTableName ||
        `${toSnakeCase(sourceResolved.ot.apiName)}_${toSnakeCase(lt.apiName)}_${toSnakeCase(targetResolved.ot.apiName)}`;
      const srcCol = linkMap.joinSourceColumnName || `${toSnakeCase(sourceResolved.ot.apiName)}_${toSnakeCase(sourcePk.columnName)}`;
      const tgtCol = linkMap.joinTargetColumnName || `${toSnakeCase(targetResolved.ot.apiName)}_${toSnakeCase(targetPk.columnName)}`;

      lines.push(`create table if not exists ${quoteIdent(joinTableName)} (`);
      lines.push(`  ${quoteIdent(srcCol)} ${sourcePk.sqlType} not null,`);
      lines.push(`  ${quoteIdent(tgtCol)} ${targetPk.sqlType} not null,`);
      lines.push(`  primary key (${quoteIdent(srcCol)}, ${quoteIdent(tgtCol)}),`);
      lines.push(
        `  constraint ${quoteIdent(`${joinTableName}_${srcCol}_fkey`)} foreign key (${quoteIdent(
          srcCol
        )}) references ${quoteIdent(sourceTable)} (${quoteIdent(sourcePk.columnName)})`
      );
      lines.push(
        `    on update cascade on delete cascade,`
      );
      lines.push(
        `  constraint ${quoteIdent(`${joinTableName}_${tgtCol}_fkey`)} foreign key (${quoteIdent(
          tgtCol
        )}) references ${quoteIdent(targetTable)} (${quoteIdent(targetPk.columnName)})`
      );
      lines.push(`    on update cascade on delete cascade`);
      lines.push(`);`);
      lines.push(``);
      continue;
    }

    const fkOn = linkMap.foreignKeyPlacement || "SOURCE";
    const fkTableName = fkOn === "TARGET" ? targetTable : sourceTable;
    const fkTableId = fkOn === "TARGET" ? lt.targetTypeId : lt.sourceTypeId;
    const refTableName = fkOn === "TARGET" ? sourceTable : targetTable;
    const refPk = fkOn === "TARGET" ? sourcePk : targetPk;

    let fkColumnName = linkMap.foreignKeyColumnName;
    if (!fkColumnName) {
      const fkPropId = lt.foreignKeyPropertyId;
      if (fkOn === "SOURCE" && fkPropId) {
        const sourceTableMap = effectiveMapping.tables[lt.sourceTypeId];
        fkColumnName = sourceTableMap?.columns?.[fkPropId]?.columnName;
      }
      if (!fkColumnName) fkColumnName = `${toSnakeCase(refTableName)}_${toSnakeCase(refPk.columnName)}`;
    }

    lines.push(`alter table ${quoteIdent(fkTableName)}`);
    lines.push(`  add column if not exists ${quoteIdent(fkColumnName)} ${refPk.sqlType};`);
    lines.push(`alter table ${quoteIdent(fkTableName)}`);
    lines.push(
      `  add constraint ${quoteIdent(`${fkTableName}_${fkColumnName}_fkey`)} foreign key (${quoteIdent(
        fkColumnName
      )}) references ${quoteIdent(refTableName)} (${quoteIdent(refPk.columnName)});`
    );
    lines.push(``);

    if (fkTableId && !effectiveMapping.tables[fkTableId]) {
      warnings.push(`LinkType ${lt.apiName} 外键表映射缺失`);
    }
  }

  return { ddl: lines.join("\n"), warnings };
}

export function generateDataDictionaryMarkdown(meta: MetaCore, mapping?: OrmMapping) {
  const effectiveMapping = mapping || buildDefaultOrmMapping(meta);
  const lines: string[] = [];

  lines.push(`# 数据字典（PostgreSQL）`);
  lines.push(``);
  lines.push(`- dialect: postgres`);
  lines.push(`- scenario: ${meta.scenario || "custom"}`);
  lines.push(`- exportedAt: ${new Date().toISOString()}`);
  lines.push(``);

  for (const ot of meta.objectTypes || []) {
    const table = effectiveMapping.tables[ot.id];
    if (!table) continue;
    const pk = computePkColumn(meta, effectiveMapping, ot.id);

    lines.push(`## ${ot.displayName || ot.apiName}`);
    lines.push(``);
    lines.push(`- ObjectType: ${ot.apiName}`);
    lines.push(`- Table: ${table.tableName}`);
    lines.push(`- Primary Key: ${pk.columnName} (${pk.sqlType})`);
    lines.push(``);
    lines.push(`| 字段 | 类型 | 必填 | 语义字段 | 描述 |`);
    lines.push(`|---|---|---|---|---|`);

    const props = ot.properties || [];
    for (const p of props) {
      const col = table.columns[p.id];
      const colName = col?.columnName || defaultColumnName(p.apiName || p.id);
      const sqlType = sqlTypeForProperty(p, col?.sqlType);
      const required = (p as any)?.required ? "Y" : "";
      lines.push(`| ${colName} | ${sqlType} | ${required} | ${p.apiName} | ${(p as any)?.description || ""} |`);
    }
    lines.push(``);
  }

  if ((meta.linkTypes || []).length) {
    lines.push(`# 关系说明`);
    lines.push(``);
    lines.push(`| 关系 | Source | Target | 基数 | 映射策略 |`);
    lines.push(`|---|---|---|---|---|`);
    for (const lt of meta.linkTypes || []) {
      const source = meta.objectTypes.find((o) => o.id === lt.sourceTypeId);
      const target = meta.objectTypes.find((o) => o.id === lt.targetTypeId);
      const linkMap = effectiveMapping.links[lt.id];
      let strategy = "";
      if (lt.cardinality === "MANY_TO_MANY") {
        strategy = `JOIN(${linkMap?.joinTableName || ""})`;
      } else {
        strategy = `${(linkMap?.foreignKeyPlacement || "SOURCE").toLowerCase()}_fk(${linkMap?.foreignKeyColumnName || ""})`;
      }
      lines.push(
        `| ${lt.apiName} | ${source?.apiName || ""} | ${target?.apiName || ""} | ${lt.cardinality} | ${strategy} |`
      );
    }
    lines.push(``);
  }

  return lines.join("\n");
}
